# Generated by Django 3.0.5 on 2020-07-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0002_written'),
    ]

    operations = [
        migrations.AlterField(
            model_name='written',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
