# Generated by Django 3.0.5 on 2020-07-05 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0003_auto_20200705_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='written',
            old_name='title',
            new_name='content',
        ),
    ]
