# Generated by Django 3.0.5 on 2020-07-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0005_auto_20200705_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='written',
            name='content',
            field=models.CharField(default='ABC', max_length=50),
        ),
    ]
