# Generated by Django 3.0.5 on 2020-07-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todolist', '0006_auto_20200706_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='written',
            name='content',
        ),
        migrations.AddField(
            model_name='written',
            name='todo',
            field=models.TextField(default='ABC'),
            preserve_default=False,
        ),
    ]
